### ISSUE TITLE
non-translateable strings

### ISSUE THREAD

**Issue by prescott66** [holylobster/nuntius-android#9]
These strings are shown in app, but they are not translateable (not included in values/strings.xml).
"Minimum notification priority" => "Min", "Low", "Default", "High", "Max"
"Running with "x" connections"  => Under Enable Nuntius switch

**Comment by nacho** [comment]
Yes we should definitely fix it.

**Comment by flyingrub** [comment]
fixed : https://github.com/holylobster/nuntius-android/commit/9eb682ceac7dd1831a6876bc8b3847dfa5091660

**Comment by nacho** [comment]
Closing then. Thanks.

**Comment by prescott66** [comment]
i still cant find string "Minimum notification priority" in resources

**Comment by nacho** [comment]
Reopening then.

**Comment by flyingrub** [comment]
i's in my pull request, https://github.com/flyingrub/nuntius-android/commit/351626c742733695c8e21547f92944aaf08e769e

**Comment by Kurtpenter** [comment]
Fixed by flyingrub. (We still lack some translations however)
